### ISSUE TITLE
understanding blueprint colourscheme

### ISSUE THREAD

**Issue by kbuzzard** [ImperialCollegeLondon/FLT#69]
This code
```latex
\begin{lemma}
    \label{ZHat.e_not_in_Int}
    \lean{ZHat.e_not_in_Int}
    \uses{ZHat.e}
    \leanok
    The element $(e_N)_N$ of $\Zhat$ is not in $\Z$.
\end{lemma}
\begin{proof}\notready
    I don't have a proof of this but it doesn't look too bad; maybe I'm wrong
    and it's hard? We will not need it later on.
\end{proof}
```

produces (on FLT) an oval with a green border (fine) but a blue interior. I want that interior to be orange or red or something. 

In fact there seem to be two kinds of `\notready` proofs -- one is "I didn't write the LaTeX yet, feel free to write it for me" and the other is "this is a multi-year project, please see the discussion link". 
Maybe I want `\needsLaTeX` to be orange, and `\noplans` to be grey?

Can I also edit the legend to explain my personal colour system?

**Comment by pitmonticone** [comment]
> I want that interior to be orange or red or something.

This is the current (default) colour scheme: 

1. **Statement Status**
   - **Blue border**: The statement of the result is ready to be formalized; all prerequisites are complete.
   - **Orange border**: The statement of the result is not ready to be formalised; additional work is required on the blueprint.
   - **Green border**: The statement of the result has been formalised.
2. **Proof Status**
   - **Blue background**: The proof of the result is ready to be formalised; all prerequisites are complete.
   - **Green background**: The proof of the result has been formalised.
    - **Dark green background**: The proof of the result and all its ancestors have been formalized.
    
We can change this scheme very easily. If I understand you correctly, you want to change the **Blue background** into an **Orange / Red background**, right? 

> In fact there seem to be two kinds of \notready proofs -- one is "I didn't write the LaTeX yet, feel free to write it for me" and the other is "this is a multi-year project, please see the discussion link". Maybe I want \needsLaTeX to be orange, and \noplans to be grey?

This is a little bit trickier because it requires changes upstream in the LeanBlueprint library. 

> Can I also edit the legend to explain my personal colour system?

Sure, I can add it to the `web.tex` preamble so that you can change the colours as you like.

**Comment by pitmonticone** [comment]
claim

**Comment by pitmonticone** [comment]
propose #261
